language: generic
sudo: required
services:
  - docker

before_install:
  - cd kubernetes_course/client && docker build -t test_client -f Dockerfile.dev .

script:
  - docker run -e CI=true test_client npm run test
