version: '3'
services:
  client-app:
    build:
      context: .  # Where your project files are
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app